name: "Publish using reprepro"
description: "Creates, and manages a apt repo with reprepro"
inputs:
  gpg_priv:
    description: "GPG private signing key"
    required: true
  gpg_passphrase:
    description: "Passphrase of the signing key"
    required: true
  state:
    description: "Used to decide which component to deploy as"
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
